//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCC.PRZTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\temp")]
        public string WORKSPACE_PATH {
            get {
                return ((string)(this["WORKSPACE_PATH"]));
            }
            set {
                this["WORKSPACE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WORKSPACE_DISPLAY_MODE {
            get {
                return ((int)(this["WORKSPACE_DISPLAY_MODE"]));
            }
            set {
                this["WORKSPACE_DISPLAY_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string DEFAULT_SELRULE_MIN_THRESHOLD {
            get {
                return ((string)(this["DEFAULT_SELRULE_MIN_THRESHOLD"]));
            }
            set {
                this["DEFAULT_SELRULE_MIN_THRESHOLD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string COST_CONSTANT_VALUE {
            get {
                return ((string)(this["COST_CONSTANT_VALUE"]));
            }
            set {
                this["COST_CONSTANT_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string DEFAULT_CF_MIN_THRESHOLD {
            get {
                return ((string)(this["DEFAULT_CF_MIN_THRESHOLD"]));
            }
            set {
                this["DEFAULT_CF_MIN_THRESHOLD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string DEFAULT_CF_GOAL {
            get {
                return ((string)(this["DEFAULT_CF_GOAL"]));
            }
            set {
                this["DEFAULT_CF_GOAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string DEFAULT_TILE_AREA {
            get {
                return ((string)(this["DEFAULT_TILE_AREA"]));
            }
            set {
                this["DEFAULT_TILE_AREA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DEFAULT_TILE_AREA_UNITS {
            get {
                return ((int)(this["DEFAULT_TILE_AREA_UNITS"]));
            }
            set {
                this["DEFAULT_TILE_AREA_UNITS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NATGRID")]
        public string DEFAULT_PU_GEOMETRY_SOURCE {
            get {
                return ((string)(this["DEFAULT_PU_GEOMETRY_SOURCE"]));
            }
            set {
                this["DEFAULT_PU_GEOMETRY_SOURCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GRAPHIC")]
        public string DEFAULT_SA_GEOMETRY_SOURCE {
            get {
                return ((string)(this["DEFAULT_SA_GEOMETRY_SOURCE"]));
            }
            set {
                this["DEFAULT_SA_GEOMETRY_SOURCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string DEFAULT_SA_BUFFER_DISTANCE {
            get {
                return ((string)(this["DEFAULT_SA_BUFFER_DISTANCE"]));
            }
            set {
                this["DEFAULT_SA_BUFFER_DISTANCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KM")]
        public string DEFAULT_SA_BUFFER_DISTANCE_UNITS {
            get {
                return ((string)(this["DEFAULT_SA_BUFFER_DISTANCE_UNITS"]));
            }
            set {
                this["DEFAULT_SA_BUFFER_DISTANCE_UNITS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MAP")]
        public string DEFAULT_OUTPUTSR_SOURCE {
            get {
                return ((string)(this["DEFAULT_OUTPUTSR_SOURCE"]));
            }
            set {
                this["DEFAULT_OUTPUTSR_SOURCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string DEFAULT_NATGRID_DIMENSION {
            get {
                return ((string)(this["DEFAULT_NATGRID_DIMENSION"]));
            }
            set {
                this["DEFAULT_NATGRID_DIMENSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DEFAULT_PU_NATGRID_USE_RASTER_FORMAT {
            get {
                return ((bool)(this["DEFAULT_PU_NATGRID_USE_RASTER_FORMAT"]));
            }
            set {
                this["DEFAULT_PU_NATGRID_USE_RASTER_FORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DEFAULT_PU_CUSTOMGRID_USE_RASTER_FORMAT {
            get {
                return ((bool)(this["DEFAULT_PU_CUSTOMGRID_USE_RASTER_FORMAT"]));
            }
            set {
                this["DEFAULT_PU_CUSTOMGRID_USE_RASTER_FORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RASTER")]
        public string DEFAULT_OUTPUT_FORMAT {
            get {
                return ((string)(this["DEFAULT_OUTPUT_FORMAT"]));
            }
            set {
                this["DEFAULT_OUTPUT_FORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AREA")]
        public string DEFAULT_PU_CUSTOMGRID_TYPE {
            get {
                return ((string)(this["DEFAULT_PU_CUSTOMGRID_TYPE"]));
            }
            set {
                this["DEFAULT_PU_CUSTOMGRID_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string DEFAULT_TILE_SIDE {
            get {
                return ((string)(this["DEFAULT_TILE_SIDE"]));
            }
            set {
                this["DEFAULT_TILE_SIDE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DEFAULT_TILE_SIDE_UNITS {
            get {
                return ((int)(this["DEFAULT_TILE_SIDE_UNITS"]));
            }
            set {
                this["DEFAULT_TILE_SIDE_UNITS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NATDB_DBPATH {
            get {
                return ((string)(this["NATDB_DBPATH"]));
            }
            set {
                this["NATDB_DBPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RT_SCRATCH_FGDB {
            get {
                return ((string)(this["RT_SCRATCH_FGDB"]));
            }
            set {
                this["RT_SCRATCH_FGDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RT_RASTER_PATH {
            get {
                return ((string)(this["RT_RASTER_PATH"]));
            }
            set {
                this["RT_RASTER_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RT_ZERO_IS_NODATA {
            get {
                return ((bool)(this["RT_ZERO_IS_NODATA"]));
            }
            set {
                this["RT_ZERO_IS_NODATA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RASTER")]
        public string WTW_SPATIAL_FORMAT {
            get {
                return ((string)(this["WTW_SPATIAL_FORMAT"]));
            }
            set {
                this["WTW_SPATIAL_FORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("prz")]
        public string NATDB_DBNAME {
            get {
                return ((string)(this["NATDB_DBNAME"]));
            }
            set {
                this["NATDB_DBNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("prz_creator")]
        public string NATDB_SCHEMANAME {
            get {
                return ((string)(this["NATDB_SCHEMANAME"]));
            }
            set {
                this["NATDB_SCHEMANAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NATDB_DBTYPE {
            get {
                return ((int)(this["NATDB_DBTYPE"]));
            }
            set {
                this["NATDB_DBTYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NATDB_DBVALID {
            get {
                return ((bool)(this["NATDB_DBVALID"]));
            }
            set {
                this["NATDB_DBVALID"] = value;
            }
        }
    }
}
