//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCC.PRZTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\temp\\jcfolder")]
        public string WORKSPACE_PATH {
            get {
                return ((string)(this["WORKSPACE_PATH"]));
            }
            set {
                this["WORKSPACE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DIR")]
        public string WORKSPACE_DISPLAY_MODE {
            get {
                return ((string)(this["WORKSPACE_DISPLAY_MODE"]));
            }
            set {
                this["WORKSPACE_DISPLAY_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string DEFAULT_SELRULE_MIN_THRESHOLD {
            get {
                return ((string)(this["DEFAULT_SELRULE_MIN_THRESHOLD"]));
            }
            set {
                this["DEFAULT_SELRULE_MIN_THRESHOLD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string COST_CONSTANT_VALUE {
            get {
                return ((string)(this["COST_CONSTANT_VALUE"]));
            }
            set {
                this["COST_CONSTANT_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string DEFAULT_CF_MIN_THRESHOLD {
            get {
                return ((string)(this["DEFAULT_CF_MIN_THRESHOLD"]));
            }
            set {
                this["DEFAULT_CF_MIN_THRESHOLD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string DEFAULT_CF_GOAL {
            get {
                return ((string)(this["DEFAULT_CF_GOAL"]));
            }
            set {
                this["DEFAULT_CF_GOAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQUARE")]
        public string DEFAULT_TILE_SHAPE {
            get {
                return ((string)(this["DEFAULT_TILE_SHAPE"]));
            }
            set {
                this["DEFAULT_TILE_SHAPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string DEFAULT_TILE_AREA {
            get {
                return ((string)(this["DEFAULT_TILE_AREA"]));
            }
            set {
                this["DEFAULT_TILE_AREA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M")]
        public string DEFAULT_TILE_AREA_UNITS {
            get {
                return ((string)(this["DEFAULT_TILE_AREA_UNITS"]));
            }
            set {
                this["DEFAULT_TILE_AREA_UNITS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NATGRID")]
        public string DEFAULT_PU_GEOMETRY_SOURCE {
            get {
                return ((string)(this["DEFAULT_PU_GEOMETRY_SOURCE"]));
            }
            set {
                this["DEFAULT_PU_GEOMETRY_SOURCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GRAPHIC")]
        public string DEFAULT_SA_GEOMETRY_SOURCE {
            get {
                return ((string)(this["DEFAULT_SA_GEOMETRY_SOURCE"]));
            }
            set {
                this["DEFAULT_SA_GEOMETRY_SOURCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string DEFAULT_SA_BUFFER_DISTANCE {
            get {
                return ((string)(this["DEFAULT_SA_BUFFER_DISTANCE"]));
            }
            set {
                this["DEFAULT_SA_BUFFER_DISTANCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KM")]
        public string DEFAULT_SA_BUFFER_DISTANCE_UNITS {
            get {
                return ((string)(this["DEFAULT_SA_BUFFER_DISTANCE_UNITS"]));
            }
            set {
                this["DEFAULT_SA_BUFFER_DISTANCE_UNITS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MAP")]
        public string DEFAULT_OUTPUTSR_SOURCE {
            get {
                return ((string)(this["DEFAULT_OUTPUTSR_SOURCE"]));
            }
            set {
                this["DEFAULT_OUTPUTSR_SOURCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string DEFAULT_NATGRID_DIMENSION {
            get {
                return ((string)(this["DEFAULT_NATGRID_DIMENSION"]));
            }
            set {
                this["DEFAULT_NATGRID_DIMENSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DEFAULT_PU_USE_RASTER_FORMAT {
            get {
                return ((bool)(this["DEFAULT_PU_USE_RASTER_FORMAT"]));
            }
            set {
                this["DEFAULT_PU_USE_RASTER_FORMAT"] = value;
            }
        }
    }
}
